### ISSUE TITLE
Connect to you

### ISSUE THREAD

**Issue by yanlinly** [TTTTTAAAAAKKKKEEEENNNN/nacos-cpp-cli#1]
Hi ,I am yanlinly, the pmc of nacos. I want to be your friend. can you tell me you contact? 

my dingding: wa7tdra
my wechat: lylolyl
my email:water.lyl@alibaba-inc.com

Looking forward to your reply as soon as possible!!

**Comment by yanlinly** [comment]
Looking forward to your reply as soon as possible!!

**Comment by yanlinly** [comment]
Looking forward to your reply as soon as possible!!

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
I've added you as my friend.

I've reviewed the code in your repository, and it is identical with this one(except for some directory structure changes).
I think we can work on your repository.
